/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package callcenter;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Utworzenie nowej formatki Menu Pracownika
 * @author Ola
 */

public class PracownikMenu extends javax.swing.JFrame {
    
    Connection conn = new DatabaseConnection().connect();
    Login loginReference;
    ResultSet rs = null;
        ResultSet rs2 = null;
    PreparedStatement pst = null;
    Statement myStmt=null;
        Statement myStmt2=null;
    ResultSet myRsKod=null;
    ResultSet myRsNr=null;
    private Integer nrPracownika;
    
    public int getnrPracownika()
    {
        return nrPracownika;
    }
    /**
     * Creates new form PracownikMenu
     * @param nrPracownika
     * @param loginReferences
     * @throws java.sql.SQLException
     */
    public PracownikMenu(Integer nrPracownika, Login loginReference) throws SQLException { 
        initComponents();
        this.nrPracownika=nrPracownika;
        this.loginReference = loginReference;
        Wyswietlanie();     
        WyswietlBazaKontaktow();
        WyswietlBazaKontaktow2();
        WypelnijAnkietaComboBox();
        WyswietlAnkiety();
        WypelnijStatusComboBox();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFrame1 = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton_WypelnijAnkiete = new javax.swing.JButton();
        jTextField_Imie = new javax.swing.JTextField();
        jTextField_Nazwisko = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_NrTelefonu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_miasto = new javax.swing.JTextField();
        jTextField_NrRespondenta = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_BazaKontaktow = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_BazaKontaktow2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_LiczbaProbPolaczenia = new javax.swing.JTextField();
        jTextField_DataNastepnegoPolaczenia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_NrAnkiety = new javax.swing.JTextField();
        jComboBox_Status = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jButton_ZapiszZmiany = new javax.swing.JButton();
        jLabel_BladZapiszZmiany = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Ankiety = new javax.swing.JTable();
        jButton_WyswietlAnkiete = new javax.swing.JButton();
        jButton_Szczegoly = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox_MojeAnkiety = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_Szczegoly = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        DanePersonalne = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Im = new javax.swing.JTextField();
        jTextField_Naz = new javax.swing.JTextField();
        jTextField_Log = new javax.swing.JTextField();
        Adres = new javax.swing.JPanel();
        jTextField_UlicaNrDomu = new javax.swing.JTextField();
        jTextField_KodPocztowy = new javax.swing.JTextField();
        jTextField_Miasto = new javax.swing.JTextField();
        Języki = new javax.swing.JPanel();
        jComboBox_Języki = new javax.swing.JComboBox();
        jButton_ZatwierdzJezyki = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jJezykBlad = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList_Jezyki = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jComboBox_Edycja = new javax.swing.JComboBox();
        jButton_Edytuj = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Edytuj = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton_Wyloguj = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel11.setText("jLabel11");

        jLabel13.setText("jLabel13");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(476, 600));

        jPanel3.setPreferredSize(new java.awt.Dimension(467, 480));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Łączenie"));

        jButton_WypelnijAnkiete.setText("Wypełnj ankiete");
        jButton_WypelnijAnkiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_WypelnijAnkieteMouseClicked(evt);
            }
        });
        jButton_WypelnijAnkiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_WypelnijAnkieteActionPerformed(evt);
            }
        });

        jTextField_Imie.setEditable(false);
        jTextField_Imie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField_Nazwisko.setEditable(false);
        jTextField_Nazwisko.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField_email.setEditable(false);
        jTextField_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setText("Nr telefonu:");

        jLabel14.setText("Imię:");

        jLabel16.setText("Nazwisko:");

        jLabel17.setText("e-mail:");

        jLabel18.setText("Nr Resp.:");

        jTextField_NrTelefonu.setEditable(false);
        jTextField_NrTelefonu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("Miasto:");

        jTextField_miasto.setEditable(false);
        jTextField_miasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_miastoActionPerformed(evt);
            }
        });

        jTextField_NrRespondenta.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addComponent(jTextField_NrRespondenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_miasto, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButton_WypelnijAnkiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField_Imie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jTextField_Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_NrTelefonu)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NrTelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_Imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField_miasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_WypelnijAnkiete))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jTextField_NrRespondenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane4MouseClicked(evt);
            }
        });

        jTable_BazaKontaktow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nr telefonu", "Imię", "Nazwisko", "e-mail", "Data urodzenia", "Miasto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_BazaKontaktow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BazaKontaktowMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_BazaKontaktow);

        jTabbedPane4.addTab("Nowe kontakty", jScrollPane2);

        jTable_BazaKontaktow2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nr Respondenta", "Nr telefonu", "Imię", "Nazwisko", "email", "NrAnkiety", "Data urodzenia", "Miasto", "Data ost", "Data nast"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_BazaKontaktow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BazaKontaktow2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable_BazaKontaktow2);
        if (jTable_BazaKontaktow2.getColumnModel().getColumnCount() > 0) {
            jTable_BazaKontaktow2.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane4.addTab("Ponowienie kontaktu", jPanel10);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane o połączeniu"));

        jLabel15.setText("Data następnego tel:");

        jLabel19.setText("Liczba prób połączenia:");

        jTextField_DataNastepnegoPolaczenia.setText("YYYY-MM-DD");
        jTextField_DataNastepnegoPolaczenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DataNastepnegoPolaczeniaActionPerformed(evt);
            }
        });

        jLabel20.setText("Nr ankiety:");

        jTextField_NrAnkiety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NrAnkietyActionPerformed(evt);
            }
        });

        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wybierz status" }));

        jLabel21.setText("Status:");

        jButton_ZapiszZmiany.setText("Zapisz zmiany");
        jButton_ZapiszZmiany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ZapiszZmianyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_BladZapiszZmiany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_NrAnkiety)
                            .addComponent(jTextField_LiczbaProbPolaczenia)
                            .addComponent(jTextField_DataNastepnegoPolaczenia)
                            .addComponent(jButton_ZapiszZmiany, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_DataNastepnegoPolaczenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField_LiczbaProbPolaczenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_NrAnkiety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ZapiszZmiany, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BladZapiszZmiany)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moje połączenia", jPanel3);

        jPanel1.setPreferredSize(new java.awt.Dimension(467, 480));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        jLabel8.setText("Wszystkie:");

        jTable_Ankiety.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nr Ankiety", "Tytuł ankiety"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Ankiety);

        jButton_WyswietlAnkiete.setText("Wyświetl treść poszczególnych ankiet");
        jButton_WyswietlAnkiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_WyswietlAnkieteMouseClicked(evt);
            }
        });

        jButton_Szczegoly.setText("Szczegóły ankiety");
        jButton_Szczegoly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SzczegolyMouseClicked(evt);
            }
        });

        jLabel9.setText("Szczegóły ankiety:");

        jComboBox_MojeAnkiety.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wybierz ankiete" }));

        jList_Szczegoly.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList_Szczegoly);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_WyswietlAnkiete, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_MojeAnkiety, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Szczegoly)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_WyswietlAnkiete)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_MojeAnkiety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Szczegoly))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(589, 589, 589)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moje ankiety", jPanel1);

        jPanel4.setPreferredSize(new java.awt.Dimension(467, 480));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Moje Dane"));

        DanePersonalne.setBorder(javax.swing.BorderFactory.createTitledBorder("Dane Personalne"));

        jLabel2.setText("Nazwisko:");

        jLabel1.setText("Imię:");

        jLabel5.setText("Login:");

        jTextField_Im.setText("jTextField4");
        jTextField_Im.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ImActionPerformed(evt);
            }
        });

        jTextField_Naz.setText("jTextField5");

        jTextField_Log.setText("jTextField6");

        javax.swing.GroupLayout DanePersonalneLayout = new javax.swing.GroupLayout(DanePersonalne);
        DanePersonalne.setLayout(DanePersonalneLayout);
        DanePersonalneLayout.setHorizontalGroup(
            DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanePersonalneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Log, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jTextField_Naz, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jTextField_Im)))
        );
        DanePersonalneLayout.setVerticalGroup(
            DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanePersonalneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Im, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Naz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(DanePersonalneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        Adres.setBorder(javax.swing.BorderFactory.createTitledBorder("Adres"));

        javax.swing.GroupLayout AdresLayout = new javax.swing.GroupLayout(Adres);
        Adres.setLayout(AdresLayout);
        AdresLayout.setHorizontalGroup(
            AdresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_KodPocztowy, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jTextField_UlicaNrDomu)
                    .addComponent(jTextField_Miasto))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        AdresLayout.setVerticalGroup(
            AdresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_UlicaNrDomu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_KodPocztowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Miasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Języki.setBorder(javax.swing.BorderFactory.createTitledBorder("Języki"));

        jComboBox_Języki.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wybierz język:", "angielski", "francuski", "hiszpanski", "wegierski", "wloski", " " }));
        jComboBox_Języki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_JęzykiActionPerformed(evt);
            }
        });

        jButton_ZatwierdzJezyki.setText("Zatwierdź");
        jButton_ZatwierdzJezyki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ZatwierdzJezykiMouseClicked(evt);
            }
        });
        jButton_ZatwierdzJezyki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ZatwierdzJezykiActionPerformed(evt);
            }
        });

        jLabel4.setText("Dodaj nowy język");

        jLabel6.setText("Twoje języki:");

        jList_Jezyki.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList_Jezyki);

        javax.swing.GroupLayout JęzykiLayout = new javax.swing.GroupLayout(Języki);
        Języki.setLayout(JęzykiLayout);
        JęzykiLayout.setHorizontalGroup(
            JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JęzykiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JęzykiLayout.createSequentialGroup()
                        .addComponent(jComboBox_Języki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ZatwierdzJezyki))
                    .addGroup(JęzykiLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jJezykBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        JęzykiLayout.setVerticalGroup(
            JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JęzykiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JęzykiLayout.createSequentialGroup()
                        .addGroup(JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(JęzykiLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JęzykiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ZatwierdzJezyki)
                            .addComponent(jComboBox_Języki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jJezykBlad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Języki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(DanePersonalne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DanePersonalne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Języki, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Edycja")));

        jComboBox_Edycja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hasło", "Ulica", "NrDomu", "NrMieszkania", "Kod", "Miasto" }));
        jComboBox_Edycja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EdycjaActionPerformed(evt);
            }
        });

        jButton_Edytuj.setText("Edytuj");
        jButton_Edytuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EdytujMouseClicked(evt);
            }
        });
        jButton_Edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EdytujActionPerformed(evt);
            }
        });

        jLabel7.setText("Podaj nową wartość");

        jLabel23.setText("Powtórz nową wartość");

        jLabel24.setText("Obecna wartość");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(342, Short.MAX_VALUE)
                        .addComponent(jButton_Edytuj))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel_Edytuj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox_Edycja, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3))))))
                .addGap(39, 39, 39))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Edycja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Edytuj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Edytuj))
        );

        jButton_Wyloguj.setText("Wyloguj się");
        jButton_Wyloguj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_WylogujMouseClicked(evt);
            }
        });

        jLabel22.setText("Podaj nową wartość");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Wyloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jLabel22)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Wyloguj)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(jLabel22)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Mój profil", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_WylogujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_WylogujMouseClicked
        new Login(null, false).show();
        dispose();
    }//GEN-LAST:event_jButton_WylogujMouseClicked

    private void jButton_SzczegolyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SzczegolyMouseClicked
        // TODO add your handling code here:
        jList_Szczegoly.removeAll();
        WypelnijListeSzczegoly();
    }//GEN-LAST:event_jButton_SzczegolyMouseClicked

     /**
     * Wyswietlenie formatki z Ankieta pokazujacej tresc poszczegolnych ankiet
     */ 
    private void jButton_WyswietlAnkieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_WyswietlAnkieteMouseClicked
        // TODO add your handling code here:
        Ankieta ankieta=new Ankieta(nrPracownika);
        ankieta.setVisible(true);
    }//GEN-LAST:event_jButton_WyswietlAnkieteMouseClicked

    private void jButton_ZapiszZmianyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ZapiszZmianyMouseClicked
        try {
            // TODO add your handling code here:
            DaneOPolaczeniu();
        } catch (ParseException ex) {
            Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ZapiszZmianyMouseClicked

    private void jTextField_NrAnkietyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NrAnkietyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NrAnkietyActionPerformed

    private void jTextField_DataNastepnegoPolaczeniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DataNastepnegoPolaczeniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DataNastepnegoPolaczeniaActionPerformed

    private void jTabbedPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane4MouseClicked

     /**
     * Wypelnienie pol tekstowych w panelu Łaczenie, po wyborze danego wiersza z tabeli "Ponowienie kontaktu"
     */ 
    private void jTable_BazaKontaktow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BazaKontaktow2MouseClicked

        // TODO add your handling code here:
        int wiersz=jTable_BazaKontaktow2.getSelectedRow();
        Object NrTelefonu= jTable_BazaKontaktow2.getValueAt(wiersz, 1);
        jTextField_NrTelefonu.setText(Integer.toString((int) NrTelefonu));
        Object Imie= jTable_BazaKontaktow2.getValueAt(wiersz, 2);
        jTextField_Imie.setText((String) Imie);
        Object Nazwisko= jTable_BazaKontaktow2.getValueAt(wiersz, 3);
        jTextField_Nazwisko.setText((String) Nazwisko);
        Object email= jTable_BazaKontaktow2.getValueAt(wiersz, 4);
        jTextField_email.setText((String) email);
        Object miasto= jTable_BazaKontaktow2.getValueAt(wiersz, 7);
        jTextField_miasto.setText((String) miasto);
        Object id=jTable_BazaKontaktow2.getValueAt(wiersz, 0);
        jTextField_NrRespondenta.setText(Integer.toString((int) id));
        //}
    }//GEN-LAST:event_jTable_BazaKontaktow2MouseClicked

     /**
     * Wypelnienie pol tekstowych w panelu Łaczenie, po wyborze danego wiersza z tabeli "Nowe kontakty"
     */ 
    private void jTable_BazaKontaktowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BazaKontaktowMouseClicked
        // TODO add your handling code here:
        int wiersz=jTable_BazaKontaktow.getSelectedRow();

        Object NrTelefonu= jTable_BazaKontaktow.getValueAt(wiersz, 1);
        jTextField_NrTelefonu.setText(Integer.toString((int) NrTelefonu));
        Object Imie= jTable_BazaKontaktow.getValueAt(wiersz, 2);
        jTextField_Imie.setText((String) Imie);
        Object Nazwisko= jTable_BazaKontaktow.getValueAt(wiersz, 3);
        jTextField_Nazwisko.setText((String) Nazwisko);
        Object email= jTable_BazaKontaktow.getValueAt(wiersz, 4);
        jTextField_email.setText((String) email);
        Object miasto= jTable_BazaKontaktow.getValueAt(wiersz, 6);
        jTextField_miasto.setText((String) miasto);
        Object id=jTable_BazaKontaktow.getValueAt(wiersz, 0);
        jTextField_NrRespondenta.setText(Integer.toString((int) id));
        //
    }//GEN-LAST:event_jTable_BazaKontaktowMouseClicked

    private void jTextField_miastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_miastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_miastoActionPerformed

    private void jButton_WypelnijAnkieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_WypelnijAnkieteActionPerformed
        // TODO add your handling code here:
        int nrRespondenta=Integer.parseInt(jTextField_NrRespondenta.getText());
        AnkietaWypelnij ankieta=new AnkietaWypelnij(nrRespondenta);
        ankieta.setVisible(true);
    }//GEN-LAST:event_jButton_WypelnijAnkieteActionPerformed

    private void jButton_WypelnijAnkieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_WypelnijAnkieteMouseClicked

    }//GEN-LAST:event_jButton_WypelnijAnkieteMouseClicked

    private void jButton_EdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EdytujActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EdytujActionPerformed

     /**
     * Zatwierdzenie edycji poszczegolnych danych dla pracownika
     */ 
    private void jButton_EdytujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EdytujMouseClicked
        // TODO add your handling code here:
        if(jComboBox_Edycja.getSelectedItem().equals("Hasło"))
        {
            if(jTextField1.getText().equals("")){
                jLabel_Edytuj.setText("Wprowadź nową wartość");
            }
            else{
                try {
                    String nowaWartosc=jTextField1.getText();
                    Edycja("Haslo",nowaWartosc );
                    jLabel_Edytuj.setText("Hasło zostało zmienione");
                } catch (SQLException ex) {
                    Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            if(jTextField1.getText().equals("")){
                jLabel_Edytuj.setText("Wprowadź nową wartość");
            }
            else {
                try {
                    String doEdycji=(String) jComboBox_Edycja.getSelectedItem();
                    String nowaWartosc=jTextField1.getText();
                    Edycja(doEdycji,nowaWartosc );
                    jLabel_Edytuj.setText(doEdycji+ " zostało zmienione");
                } catch (SQLException ex) {
                    Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        Wyswietlanie();
    }//GEN-LAST:event_jButton_EdytujMouseClicked

    private void jComboBox_EdycjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EdycjaActionPerformed

    }//GEN-LAST:event_jComboBox_EdycjaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton_ZatwierdzJezykiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ZatwierdzJezykiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ZatwierdzJezykiActionPerformed

     /**
     * Zatwierdzenie edycji jezyka poszczegolnego pracownika
     */ 
    private void jButton_ZatwierdzJezykiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ZatwierdzJezykiMouseClicked
        try {
            // TODO add your handling code here:
            PokazJezyki();
            DefaultListModel listModel=new DefaultListModel();
            List <String> lista=new ArrayList();
            lista=Pobierz("Jezyk");
            for(String j: lista){
                listModel.addElement(j);
            }
                jList_Jezyki.setModel(listModel);                
        

        } catch (SQLException ex) {
            Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ZatwierdzJezykiMouseClicked

    private void jTextField_ImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ImActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ImActionPerformed

    private void jComboBox_JęzykiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_JęzykiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_JęzykiActionPerformed

    /**
     * Wypelnienie pol tekstowych w zakladce Moj Profil
     */  
    public void Wyswietlanie()
    {
        String Login="pracownik"; //SPRAWDZIC
        try{
            List <String> lista=new ArrayList();
           
            DefaultListModel listModel=new DefaultListModel();
            lista=Pobierz("Jezyk");
            for(String j: lista){
                listModel.addElement(j);
            }
            jList_Jezyki.setModel(listModel); 
            
            lista = Pobierz("Imie");
            String text=lista.get(0);
            jTextField_Im.setText(text);
            text = (String) Pobierz("Nazwisko").get(0);
            jTextField_Naz.setText(text);
            jTextField_Log.setText(Login); //SPRAWDZIC Zmienna login
            text=Pobierz("Ulica").get(0)+" "+Pobierz("NrDomu").get(0)+"/"+Pobierz("NrMieszkania").get(0);
            jTextField_UlicaNrDomu.setText(text);
            text=(String)Pobierz("Kod").get(0);
            jTextField_KodPocztowy.setText(text);
            text=(String)Pobierz("Miasto").get(0);
            jTextField_Miasto.setText(text);
        }
        catch (SQLException ex) 
        {
                JOptionPane.showMessageDialog(null, ex);
        }
    }
     /**
     * Wyswietlenie jezykow danego pracownika
     */     
    public void PokazJezyki(){
        if(jComboBox_Języki.getSelectedItem().equals("Wybierz język:"))
        {
            jJezykBlad.setText("Wybierz język");
        }
        else {

            try {
                String text=(String) jComboBox_Języki.getSelectedItem();
                if(JezykEdycja(text)==1){
                    jJezykBlad.setText("Wybrany jezyk istnieje juz w bazie");
                }
                else{
                    jJezykBlad.setText("Dodano jezyk do bazy");
                    
                }

            } catch (SQLException ex) {
                Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                Wyswietlanie();
    }
    /**
     * Wypelnienie danych w tabeli Nowe Kontakty, po pobraniu danych z bazy danych 
     */ 
    public void WyswietlBazaKontaktow() throws SQLException
    {
        try{
            String sqlCommand = "SELECT NrRespondenta, NrTelefonu,Imie, Nazwisko, email, DataUrodzenia, Miasto from respondent natural join polaczenie where DataNastepnegoPolaczenia='0000-00-00'";
            pst = conn.prepareStatement(sqlCommand);
            rs = pst.executeQuery();
            jTable_BazaKontaktow.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null, exc);
        }
    }
    /**
     * Wypelnienie danych w tabeli Ponowienie Kontaktu, po pobraniu danych z bazy danych 
     */ 
        public void WyswietlBazaKontaktow2() throws SQLException
    {    
        try{
            String sqlCommand = "select NrRespondenta, NrTelefonu, Imie, Nazwisko,email, NrAnkiety, DataUrodzenia, Miasto, DataOstatniegoPolaczenia, DataNastepnegoPolaczenia from respondent natural join polaczenie where NrPracownika="+nrPracownika+" and DataNastepnegoPolaczenia!='0000-00-00'  order by DataNastepnegoPolaczenia";
            pst = conn.prepareStatement(sqlCommand);
            rs = pst.executeQuery();
            jTable_BazaKontaktow2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null, exc);
        }
    }
    /**
     * Wypelnienie jComboBox_MojeAnkiety ankietami obslugiwanycmi przez danego pracownika
     */         
    public void WypelnijAnkietaComboBox(){
        String sql = "SELECT concat(NrAnkiety,'. ',Opis) FROM ankiety";
        try {
            //clean ComboBox
            //jComboBox_Ankieta.removeAllItems();
            //get data
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while(rs.next()){
                jComboBox_MojeAnkiety.addItem(rs.getString(1));
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "fillAnkietaComboBox() could not connect to database. " + e);
        }
    }
    /**
     * Wypelnienie jComboBox_Status mozliwymi opcjami wybpru statusu przeprowadzonego polaczenia
     */     
    public void WypelnijStatusComboBox(){
        String sql = "SELECT concat(TypStatusu,' ',OpisStatusu) FROM status_polaczenia";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                jComboBox_Status.addItem(rs.getString(1));
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "WypelnijStatusComboBox() could not connect to database. " + e);
        }        
    }
    
    /**
     * Wyświetlenie ankiet danego pracownika w tabeli jTable_Ankiety
     */ 
        public void WyswietlAnkiety() throws SQLException
    {
        try{
            String sqlCommand = "SELECT NrAnkiety, Opis from ankiety where NrPracownika="+nrPracownika;
            pst = conn.prepareStatement(sqlCommand);
            rs = pst.executeQuery();
            jTable_Ankiety.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null, exc);
        }
    }
        /**
     * Funkcja wprowadzajaca do bazy danych dane o polaczeniu po wypelnieniu poszczegolnych pol tekstowych przez uzytkownika
     */     
        public void DaneOPolaczeniu() throws ParseException
        {
            if(jTextField_DataNastepnegoPolaczenia.getText().equals("YYYY-MM-DD")|| jTextField_NrAnkiety.getText().equals("")||jTextField_LiczbaProbPolaczenia.getText().equals("")){
                jLabel_BladZapiszZmiany.setText("Wprowadź wszystkie dane");
            }
            else{
                jLabel_BladZapiszZmiany.setText("");
                try {
                    Integer typStatusu=0;
                    if(jComboBox_Status.getSelectedIndex()==0)
                    {
                        jLabel_BladZapiszZmiany.setText("Wybierz status połączenia");        
                    }
                    else{
                        typStatusu=jComboBox_Status.getSelectedIndex();
                        System.out.println(typStatusu);
                        String dataNastepnegoPolaczenia=jTextField_DataNastepnegoPolaczenia.getText();

                                DateFormat dateFrm = new SimpleDateFormat("yyyy-MM-dd");
                                java.util.Date myDate = new java.util.Date();
                                java.sql.Date sqlDate;

                                try
                                {
                                  myDate = dateFrm.parse(dataNastepnegoPolaczenia);
                                  sqlDate = new java.sql.Date(myDate.getTime());
                                }
                                catch (Exception e)
                                {
                                  sqlDate = null;
                                }
                            Integer liczbaProbPolaczenia=Integer.parseInt(jTextField_LiczbaProbPolaczenia.getText());
                            Integer nrAnkiety=Integer.parseInt(jTextField_NrAnkiety.getText());
                            Integer nrRespondenta=Integer.parseInt(jTextField_NrRespondenta.getText());
                            String sqlCommand = "INSERT INTO `polaczenie`(`NrAnkiety`, `NrPracownika`, `NrRespondenta`, `TypStatusu`, `DataOstatniegoPolaczenia`, `LiczbaProbPolaczenia`, `DataNastepnegoPolaczenia`) VALUES ("+nrAnkiety+","+nrPracownika+","+nrRespondenta+","+typStatusu+",curdate(),"+liczbaProbPolaczenia+",'"+sqlDate+"')";

                            pst = conn.prepareStatement(sqlCommand);

                        // execute the java preparedstatement
                        pst.execute();
                        jLabel_BladZapiszZmiany.setText("Dane zostaly wprowadzone!");                        
                     }
                }
                catch (SQLException ex) {
                    Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracownikMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracownikMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracownikMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracownikMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    PracownikMenu pracownik=new PracownikMenu(2, null);
                    pracownik.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adres;
    private javax.swing.JPanel DanePersonalne;
    private javax.swing.JPanel Języki;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Edytuj;
    private javax.swing.JButton jButton_Szczegoly;
    private javax.swing.JButton jButton_Wyloguj;
    private javax.swing.JButton jButton_WypelnijAnkiete;
    private javax.swing.JButton jButton_WyswietlAnkiete;
    private javax.swing.JButton jButton_ZapiszZmiany;
    private javax.swing.JButton jButton_ZatwierdzJezyki;
    private javax.swing.JComboBox jComboBox_Edycja;
    private javax.swing.JComboBox jComboBox_Języki;
    private javax.swing.JComboBox jComboBox_MojeAnkiety;
    private javax.swing.JComboBox jComboBox_Status;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jJezykBlad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BladZapiszZmiany;
    private javax.swing.JLabel jLabel_Edytuj;
    private javax.swing.JList jList1;
    private javax.swing.JList jList_Jezyki;
    private javax.swing.JList jList_Szczegoly;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable_Ankiety;
    private javax.swing.JTable jTable_BazaKontaktow;
    private javax.swing.JTable jTable_BazaKontaktow2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_DataNastepnegoPolaczenia;
    private javax.swing.JTextField jTextField_Im;
    private javax.swing.JTextField jTextField_Imie;
    private javax.swing.JTextField jTextField_KodPocztowy;
    private javax.swing.JTextField jTextField_LiczbaProbPolaczenia;
    private javax.swing.JTextField jTextField_Log;
    private javax.swing.JTextField jTextField_Miasto;
    private javax.swing.JTextField jTextField_Naz;
    private javax.swing.JTextField jTextField_Nazwisko;
    private javax.swing.JTextField jTextField_NrAnkiety;
    private javax.swing.JTextField jTextField_NrRespondenta;
    private javax.swing.JTextField jTextField_NrTelefonu;
    private javax.swing.JTextField jTextField_UlicaNrDomu;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_miasto;
    // End of variables declaration//GEN-END:variables

    public List Pobierz(String nazwa) throws SQLException{
 
        List<String> lista=new ArrayList();
        try {           
            myStmt= conn.createStatement();
            //Pobranie z bazy danych jezykow przypisanych dla danego pracownika
            if(nazwa.equals("Jezyk"))
            {
                rs = myStmt.executeQuery("SELECT " + nazwa + " FROM `jezyki` WHERE KodJezyka IN (select KodJezyka from pracownik_jezyki where NrPracownika="+nrPracownika+")");

                while (rs.next()) {
                    lista.add(rs.getString(nazwa));
                }               
            }
            else{
                rs = myStmt.executeQuery("select " + nazwa+" from pracownik where NrPracownika ="+nrPracownika);
                while (rs.next()) {
                    lista.add(rs.getString(nazwa));
                    //System.out.println(myRs.getString(nazwa));// + ", " + myRs.getString("Address"))
                }               
            }
        }
        catch(SQLException se){
        System.out.println("Brak bazy danych " + se);
         }
        return lista;
    }
    /**
     * Wyświetlenie szczegółów wybranej ankiety w jListSzczegoly
     */     
        public void WypelnijListeSzczegoly(){
        
        DefaultListModel lista= new DefaultListModel();

        try {
            if(jComboBox_MojeAnkiety.getSelectedIndex()==0)
            {
                lista.addElement("Wybierz numer ankiety"); 
                jList_Szczegoly.setModel(lista);
            }
            else{
                jList_Szczegoly.removeAll();
                int nrAnkiety=jComboBox_MojeAnkiety.getSelectedIndex();
                String sqlCommand = "SELECT DataRozpoczecia, DataZamkniecia, NrZleceniodawcy from ankiety where NrAnkiety="+nrAnkiety;
                pst = conn.prepareStatement(sqlCommand);
                rs = pst.executeQuery();
                rs.next();
                    String dataRozpoczecia=rs.getString("DataRozpoczecia");
                    String dataZakonczenia=rs.getString("DataZamkniecia");
                    String nrZleceniodawcy=Integer.toString(rs.getInt("NrZleceniodawcy"));

                lista.addElement("Nr Ankiety: "+nrAnkiety); 
                lista.addElement("Data rozpoczecia ankiety: "+dataRozpoczecia); 
                lista.addElement("Data zakonczenia ankiety: "+dataZakonczenia); 
                
                sqlCommand = "SELECT Firma from zleceniodawca where NrZleceniodawcy="+nrZleceniodawcy;    
                pst = conn.prepareStatement(sqlCommand);
                rs = pst.executeQuery();
                rs.next(); 
                String nazwaZleceniodawcy=rs.getString("Firma");
                lista.addElement("Nazwa Zleceniodawcy: "+nazwaZleceniodawcy); 
                jList_Szczegoly.setModel(lista);   
            }
        } catch (SQLException ex) {
            Logger.getLogger(PracownikMenu.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
        
    public int JezykEdycja (String jezyk) throws SQLException
   {
        try {
           
            System.out.println("Baza Danych połączona");
            
            myStmt= conn.createStatement();
            rs = myStmt.executeQuery("SELECT Jezyk FROM `jezyki` WHERE KodJezyka IN (select KodJezyka from pracownik_jezyki where NrPracownika ="+nrPracownika+")");

                while (rs.next()) {
                    if(rs.getString("Jezyk").equals(jezyk)){
                        System.out.println("jezyk istnieje juz w bazie");
                        return 1;
                    } 
                }

            myStmt2= conn.createStatement();
            //zapytanie zwracajace kod jezyka wybranego przez uzytkownika
            rs2 = myStmt2.executeQuery("SELECT KodJezyka from jezyki where Jezyk like'"+jezyk+"'");
            rs2.next();
            String Kod=rs2.getString("KodJezyka");
            //dodanie wybranego jezyka do bazy
            //System.out.println("kod jezyka: "+Kod);
            myStmt2.execute("INSERT INTO `pracownik_jezyki`(`NrPracownika`, `KodJezyka`) VALUES ("+nrPracownika+",'"+Kod+"')");
        }
        catch(SQLException se){
        System.out.println("Brak bazy danych " + se);
         }
        return 0;
    }
    public void Edycja(String pole, String wartosc) throws SQLException {

        try {
            conn =DriverManager.getConnection("jdbc:mysql://localhost/callcenter","root", "");
            System.out.println("Baza Danych połączona");
            
            myStmt= conn.createStatement();
            if(pole.equals("Haslo"))
            {
                myStmt.execute("UPDATE `login` SET `Haslo`='"+wartosc+"' WHERE login='pracownik'");
            }
            else{
                myStmt.execute("UPDATE `pracownik` SET "+pole+"='"+wartosc+"' WHERE NrPracownika="+nrPracownika);
            }

        }
        catch(SQLException se){
        System.out.println("Brak bazy danych " + se);
         }       
     }
}
